// @ts-check
// DWDM Academy sidebar — tự sinh từ cấu trúc thư mục docs/.
// Thứ tự cấp/module điều khiển bằng _category_.json và front-matter sidebar_position.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  courseSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
